version: "2"
run:
  issues-exit-code: 1
linters:
  default: none
  enable:
    - staticcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - sloglint
  settings:
    staticcheck:
      checks:
        - all
        - '-QF1003'
        - '-QF1008'
        - '-ST1003'
    gosec:
      excludes:
        - G115
        - G602
    sloglint:
      attr-only: true
      no-mixed-args: true
      static-msg: true
      no-global: all
      custom-funcs:
        - name: github.com/consensys/gnark/internal/logger.Trace
          msg-pos: 1
          args-pos: 2
  exclusions:
    generated: disable
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: disable
    paths:
      - third_party$
      - builtin$
      - examples$
