linters:
  # disable-all: true
  enable-all: true
  disable:
    - varnamelen
    - wrapcheck
    - testpackage
    - thelper
    - paralleltest
    - nonamedreturns
    - nosnakecase
    - nlreturn
    - gomnd
    - goerr113
  # enable:
  #   - gofmt
  #   - staticcheck
  #   - gosec
  #   - gosimple
  #   - govet
  #   - ineffassign

run:
  issues-exit-code: 1