version: 2

linters:
  disable-all: true
  enable:
    - staticcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    
linters-settings:
  gosec:
    excludes:
      - G115 # Conversions from int -> uint etc.
issues:
  exclude-generated: disable
run:
  issues-exit-code: 1
