version: "2"
run:
  issues-exit-code: 1
linters:
  default: none
  enable:
    - staticcheck
    - gosec
    - govet
    - ineffassign
    - misspell
  settings:
    staticcheck:
      checks:
        - all
        - '-QF1003'
        - '-QF1008'
        - '-ST1003'
    gosec:
      excludes:
        - G115
        - G602
  exclusions:
    generated: disable
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: disable
    paths:
      - third_party$
      - builtin$
      - examples$
