package gkrapi_test

import (
	"os"
	"testing"

	"github.com/consensys/gnark-crypto/ecc"
	"github.com/consensys/gnark/backend/plonk"
	"github.com/stretchr/testify/require"
)

// TestGkrCircuitDeserialization verifies that GKR blueprint types are properly
// registered for CBOR deserialization when only importing the constraint system
// package (via plonk.NewCS), without importing gkrapi.
//
// This test reads a pre-generated constraint system file that contains GKR blueprints.
// The file is generated by internal/gkr/test_vectors/generate.go during code generation.
func TestGkrCircuitDeserialization(t *testing.T) {
	// Open the pre-generated constraint system file
	f, err := os.Open("../../internal/gkr/test_vectors/testdata/gkr_circuit_bn254.scs")
	require.NoError(t, err)
	defer f.Close()

	// Create a new constraint system - this imports constraint/bn254 which
	// should trigger GKR blueprint registration via init()
	ccs := plonk.NewCS(ecc.BN254)

	// Deserialize - this will panic if GKR blueprint types aren't registered
	n, err := ccs.ReadFrom(f)
	require.NoError(t, err)
	require.NotZero(t, n)
}
