// Copyright 2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by gnark DO NOT EDIT

package bls12377

import (
	"fmt"
	"math/big"
	"math/bits"
	"math/rand"

	fp "github.com/consensys/gnark-crypto/ecc/bls12-377/fp"
	fr "github.com/consensys/gnark-crypto/ecc/bls12-377/fr"
)

type FieldElementCaseJSON struct {
	Name           string `json:"name"`
	ABytesLE       string `json:"a_bytes_le"`
	BBytesLE       string `json:"b_bytes_le"`
	EqualBytesLE   string `json:"equal_bytes_le"`
	AddBytesLE     string `json:"add_bytes_le"`
	SubBytesLE     string `json:"sub_bytes_le"`
	NegABytesLE    string `json:"neg_a_bytes_le"`
	DoubleABytesLE string `json:"double_a_bytes_le"`
	MulBytesLE     string `json:"mul_bytes_le"`
	SquareABytesLE string `json:"square_a_bytes_le"`
}

type NormalizeCaseJSON struct {
	Name            string `json:"name"`
	InputBytesLE    string `json:"input_bytes_le"`
	ExpectedBytesLE string `json:"expected_bytes_le"`
}

type ConvertCaseJSON struct {
	Name         string `json:"name"`
	RegularBytes string `json:"regular_bytes_le"`
	MontBytes    string `json:"mont_bytes_le"`
}

type FieldOpsVectorsJSON struct {
	ElementCases      []FieldElementCaseJSON `json:"element_cases"`
	EdgeCases         []FieldElementCaseJSON `json:"edge_cases"`
	DifferentialCases []FieldElementCaseJSON `json:"differential_cases"`
	NormalizeCases    []NormalizeCaseJSON    `json:"normalize_cases"`
	ConvertCases      []ConvertCaseJSON      `json:"convert_cases"`
}

type VectorCaseJSON struct {
	Name               string   `json:"name"`
	RegularInputs      []string `json:"regular_inputs_le"`
	MontInputs         []string `json:"mont_inputs_le"`
	MontFactors        []string `json:"mont_factors_le"`
	AddExpected        []string `json:"add_expected_le"`
	SubExpected        []string `json:"sub_expected_le"`
	MulExpected        []string `json:"mul_expected_le"`
	ToMontExpected     []string `json:"to_mont_expected_le"`
	FromMontExpected   []string `json:"from_mont_expected_le"`
	BitReverseExpected []string `json:"bit_reverse_expected_le"`
}

type VectorOpsJSON struct {
	VectorCases []VectorCaseJSON `json:"vector_cases"`
}

func BuildFROpsVectors() FieldOpsVectorsJSON {
	rng := rand.New(rand.NewSource(20260406))
	return buildFieldOpsVectors(
		buildFRElementCase,
		buildFRConvertCase,
		buildFRDifferentialCases(rng, 32),
		frRegularHex,
		frModulus,
		frQMinusOne,
		frQMinus,
		frFloorHalfModulus,
		frCeilHalfModulus,
	)
}

func BuildFPOpsVectors() FieldOpsVectorsJSON {
	rng := rand.New(rand.NewSource(20260407))
	return buildFieldOpsVectors(
		buildFPElementCase,
		buildFPConvertCase,
		buildFPDifferentialCases(rng, 32),
		fpRegularHex,
		fpModulus,
		fpQMinusOne,
		fpQMinus,
		fpFloorHalfModulus,
		fpCeilHalfModulus,
	)
}

func buildFieldOpsVectors(
	buildElementCase func(string, *big.Int, *big.Int) FieldElementCaseJSON,
	buildConvertCase func(string, *big.Int) ConvertCaseJSON,
	differentialCases []FieldElementCaseJSON,
	regularHex func(*big.Int) string,
	modulus func() *big.Int,
	qMinusOne func() *big.Int,
	qMinus func(uint64) *big.Int,
	floorHalf func() *big.Int,
	ceilHalf func() *big.Int,
) FieldOpsVectorsJSON {
	return FieldOpsVectorsJSON{
		ElementCases: []FieldElementCaseJSON{
			buildElementCase("zero_zero", regularUint64(0), regularUint64(0)),
			buildElementCase("zero_one", regularUint64(0), regularUint64(1)),
			buildElementCase("one_one", regularUint64(1), regularUint64(1)),
			buildElementCase("two_five", regularUint64(2), regularUint64(5)),
			buildElementCase("neg_one_one", qMinusOne(), regularUint64(1)),
			buildElementCase("seven_five", regularUint64(7), regularUint64(5)),
		},
		EdgeCases: []FieldElementCaseJSON{
			buildElementCase("carry32_plus_one", pow2MinusOne(32), regularUint64(1)),
			buildElementCase("carry64_plus_one", pow2MinusOne(64), regularUint64(1)),
			buildElementCase("carry128_plus_one", pow2MinusOne(128), regularUint64(1)),
			buildElementCase("carry192_plus_one", pow2MinusOne(192), regularUint64(1)),
			buildElementCase("q_minus_two_plus_three", qMinus(2), regularUint64(3)),
			buildElementCase("q_minus_one_q_minus_one", qMinusOne(), qMinusOne()),
			buildElementCase("q_minus_two_q_minus_one", qMinus(2), qMinusOne()),
			buildElementCase("half_q_floor_half_q_ceil", floorHalf(), ceilHalf()),
		},
		DifferentialCases: differentialCases,
		NormalizeCases: []NormalizeCaseJSON{
			{Name: "zero", InputBytesLE: regularHex(regularUint64(0)), ExpectedBytesLE: regularHex(regularUint64(0))},
			{Name: "one", InputBytesLE: regularHex(regularUint64(1)), ExpectedBytesLE: regularHex(regularUint64(1))},
			{Name: "q_minus_one", InputBytesLE: regularHex(qMinusOne()), ExpectedBytesLE: regularHex(qMinusOne())},
			{Name: "q", InputBytesLE: regularHex(modulus()), ExpectedBytesLE: regularHex(regularUint64(0))},
			{Name: "q_plus_one", InputBytesLE: regularHex(addBig(modulus(), regularUint64(1))), ExpectedBytesLE: regularHex(regularUint64(1))},
			{Name: "two_q_minus_one", InputBytesLE: regularHex(subBig(mulBig(modulus(), regularUint64(2)), regularUint64(1))), ExpectedBytesLE: regularHex(qMinusOne())},
		},
		ConvertCases: []ConvertCaseJSON{
			buildConvertCase("zero", regularUint64(0)),
			buildConvertCase("one", regularUint64(1)),
			buildConvertCase("two", regularUint64(2)),
			buildConvertCase("five", regularUint64(5)),
			buildConvertCase("seven", regularUint64(7)),
			buildConvertCase("q_minus_one", qMinusOne()),
		},
	}
}

func BuildFRVectorOps() VectorOpsJSON {
	return VectorOpsJSON{
		VectorCases: []VectorCaseJSON{
			buildFRVectorCase("n8_random", 8, rand.New(rand.NewSource(2026040601))),
			buildFRVectorCase("n16_random", 16, rand.New(rand.NewSource(2026040602))),
		},
	}
}

func buildFRVectorCase(name string, size int, rng *rand.Rand) VectorCaseJSON {
	out := VectorCaseJSON{
		Name:               name,
		RegularInputs:      make([]string, size),
		MontInputs:         make([]string, size),
		MontFactors:        make([]string, size),
		AddExpected:        make([]string, size),
		SubExpected:        make([]string, size),
		MulExpected:        make([]string, size),
		ToMontExpected:     make([]string, size),
		FromMontExpected:   make([]string, size),
		BitReverseExpected: make([]string, size),
	}
	for i := 0; i < size; i++ {
		aRegular := randomFRFieldBigInt(rng)
		bRegular := randomFRFieldBigInt(rng)
		var aMont, bMont fr.Element
		aMont.SetBigInt(aRegular)
		bMont.SetBigInt(bRegular)
		var add, sub, mul fr.Element
		add.Add(&aMont, &bMont)
		sub.Sub(&aMont, &bMont)
		mul.Mul(&aMont, &bMont)
		out.RegularInputs[i] = frRegularHex(aRegular)
		out.MontInputs[i] = frElementHex(aMont)
		out.MontFactors[i] = frElementHex(bMont)
		out.AddExpected[i] = frElementHex(add)
		out.SubExpected[i] = frElementHex(sub)
		out.MulExpected[i] = frElementHex(mul)
		out.ToMontExpected[i] = frElementHex(aMont)
		out.FromMontExpected[i] = frRegularHex(aRegular)
	}
	logCount := bits.Len(uint(size)) - 1
	for i := 0; i < size; i++ {
		j := int(bits.Reverse64(uint64(i)) >> (64 - logCount))
		out.BitReverseExpected[i] = out.MontInputs[j]
	}
	return out
}

func buildFRElementCase(name string, aRegular, bRegular *big.Int) FieldElementCaseJSON {
	aMont := frToMont(aRegular)
	bMont := frToMont(bRegular)
	var add, sub, negA, dblA, mul, sqA fr.Element
	add.Add(&aMont, &bMont)
	sub.Sub(&aMont, &bMont)
	negA.Neg(&aMont)
	dblA.Double(&aMont)
	mul.Mul(&aMont, &bMont)
	sqA.Square(&aMont)
	equal := frZeroMont()
	if aMont.Equal(&bMont) {
		equal.SetUint64(1)
	}
	return FieldElementCaseJSON{Name: name, ABytesLE: frElementHex(aMont), BBytesLE: frElementHex(bMont), EqualBytesLE: frElementHex(equal), AddBytesLE: frElementHex(add), SubBytesLE: frElementHex(sub), NegABytesLE: frElementHex(negA), DoubleABytesLE: frElementHex(dblA), MulBytesLE: frElementHex(mul), SquareABytesLE: frElementHex(sqA)}
}

func buildFPElementCase(name string, aRegular, bRegular *big.Int) FieldElementCaseJSON {
	aMont := fpToMont(aRegular)
	bMont := fpToMont(bRegular)
	var add, sub, negA, dblA, mul, sqA fp.Element
	add.Add(&aMont, &bMont)
	sub.Sub(&aMont, &bMont)
	negA.Neg(&aMont)
	dblA.Double(&aMont)
	mul.Mul(&aMont, &bMont)
	sqA.Square(&aMont)
	equal := fpZeroMont()
	if aMont.Equal(&bMont) {
		equal.SetUint64(1)
	}
	return FieldElementCaseJSON{Name: name, ABytesLE: fpElementHex(aMont), BBytesLE: fpElementHex(bMont), EqualBytesLE: fpElementHex(equal), AddBytesLE: fpElementHex(add), SubBytesLE: fpElementHex(sub), NegABytesLE: fpElementHex(negA), DoubleABytesLE: fpElementHex(dblA), MulBytesLE: fpElementHex(mul), SquareABytesLE: fpElementHex(sqA)}
}

func buildFRConvertCase(name string, regular *big.Int) ConvertCaseJSON {
	return ConvertCaseJSON{Name: name, RegularBytes: frRegularHex(regular), MontBytes: frElementHex(frToMont(regular))}
}

func buildFPConvertCase(name string, regular *big.Int) ConvertCaseJSON {
	return ConvertCaseJSON{Name: name, RegularBytes: fpRegularHex(regular), MontBytes: fpElementHex(fpToMont(regular))}
}

func buildFRDifferentialCases(rng *rand.Rand, count int) []FieldElementCaseJSON {
	out := make([]FieldElementCaseJSON, count)
	for i := 0; i < count; i++ {
		a := randomFRFieldBigInt(rng)
		b := randomFRFieldBigInt(rng)
		if i%7 == 0 {
			b = new(big.Int).Set(a)
		}
		out[i] = buildFRElementCase(fmt.Sprintf("random_%02d", i), a, b)
	}
	return out
}

func buildFPDifferentialCases(rng *rand.Rand, count int) []FieldElementCaseJSON {
	out := make([]FieldElementCaseJSON, count)
	for i := 0; i < count; i++ {
		a := randomFPFieldBigInt(rng)
		b := randomFPFieldBigInt(rng)
		if i%7 == 0 {
			b = new(big.Int).Set(a)
		}
		out[i] = buildFPElementCase(fmt.Sprintf("random_%02d", i), a, b)
	}
	return out
}

func frRegularHex(v *big.Int) string { return regularHex(v, 32) }
func fpRegularHex(v *big.Int) string { return regularHex(v, 48) }
