package uintexp

import (
	"fmt"
	"math/big"
	"sync"
)

// omegaCache caches the derived subgroup generators keyed by (modulus, k). The
// derivation is deterministic, but hints may run concurrently at solving time
// so the cache must be safe for concurrent use.
var omegaCache sync.Map // map[string]*big.Int, key = q.String() + "/" + k

// twoAdicity returns v2(q-1), the 2-adicity of the multiplicative group of the
// field with modulus q.
func twoAdicity(q *big.Int) int {
	qm1 := new(big.Int).Sub(q, big.NewInt(1))
	if qm1.Sign() <= 0 {
		return 0
	}
	return int(qm1.TrailingZeroBits())
}

// omega returns a fixed element of multiplicative order exactly 2^k in the
// field with odd prime modulus q. It errors if the multiplicative group has
// insufficient 2-adicity, i.e. v2(q-1) < k.
//
// The derivation is deterministic from q and k alone (so that in-circuit code
// and hints agree): let s = v2(q-1) and let n be the smallest quadratic
// nonresidue in {2, 3, 4, ...} by the Euler criterion. Then g = n^((q-1)/2^s)
// generates the 2-Sylow subgroup of F_q^* (order 2^s) and ω = g^(2^(s-k)) has
// order exactly 2^k.
func omega(q *big.Int, k int) (*big.Int, error) {
	if k <= 0 {
		return nil, fmt.Errorf("width must be positive, got %d", k)
	}
	s := twoAdicity(q)
	if s < k {
		return nil, fmt.Errorf("field 2-adicity %d is insufficient for width %d", s, k)
	}
	cacheKey := q.String() + "/" + fmt.Sprint(k)
	if v, ok := omegaCache.Load(cacheKey); ok {
		return v.(*big.Int), nil
	}
	one := big.NewInt(1)
	qm1 := new(big.Int).Sub(q, one)
	euler := new(big.Int).Rsh(qm1, 1) // (q-1)/2
	// smallest quadratic nonresidue
	n := big.NewInt(2)
	t := new(big.Int)
	for {
		t.Exp(n, euler, q)
		if t.Cmp(qm1) == 0 { // n^((q-1)/2) == -1 mod q
			break
		}
		n.Add(n, one)
	}
	// generator of the 2-Sylow subgroup, order 2^s
	oddPart := new(big.Int).Rsh(qm1, uint(s)) // (q-1)/2^s
	g := new(big.Int).Exp(n, oddPart, q)
	// element of order exactly 2^k
	w := g.Exp(g, new(big.Int).Lsh(one, uint(s-k)), q)
	omegaCache.Store(cacheKey, w)
	return w, nil
}

// decodeExp returns the discrete logarithm a ∈ [0, 2^k) of v in base ω, i.e.
// v = ω^a, where ω = omega(q, k). It errors if v is not in the subgroup
// generated by ω.
//
// The group is cyclic of 2-power order, so the discrete logarithm is computed
// by bit-peeling (Pohlig-Hellman): for i = 0..k-1 the value
// (v·ω^(-x))^(2^(k-1-i)) is ±1, and the sign reads off bit i of a.
func decodeExp(q *big.Int, k int, v *big.Int) (*big.Int, error) {
	w, err := omega(q, k)
	if err != nil {
		return nil, err
	}
	if v.Sign() == 0 || v.Cmp(q) >= 0 {
		return nil, fmt.Errorf("value out of field range or zero")
	}
	one := big.NewInt(1)
	qm1 := new(big.Int).Sub(q, one)
	wInv := new(big.Int).ModInverse(w, q)
	a := new(big.Int)
	rem := new(big.Int).Set(v) // v·ω^(-a mod 2^i), invariant: rem^(2^(k-i)) == 1 required
	t := new(big.Int)
	for i := 0; i < k; i++ {
		t.Exp(rem, new(big.Int).Lsh(one, uint(k-1-i)), q)
		switch {
		case t.Cmp(one) == 0:
			// bit i is 0
		case t.Cmp(qm1) == 0:
			// bit i is 1
			a.SetBit(a, i, 1)
			rem.Mul(rem, t.Exp(wInv, new(big.Int).Lsh(one, uint(i)), q)).Mod(rem, q)
		default:
			return nil, fmt.Errorf("value is not in the subgroup of order 2^%d", k)
		}
	}
	if rem.Cmp(one) != 0 {
		return nil, fmt.Errorf("value is not in the subgroup of order 2^%d", k)
	}
	return a, nil
}
