## This is an example Dockerfile 
## build from root of repo :
# docker build -f gnarkd/Dockerfile.example -t gnarkd .
## experiment like so, in gnarkd/:
# docker run -it --rm  -p9002:9002 -p9001:9001 --mount type=bind,source="$(pwd)"/circuits,target=/root/circuits --mount type=bind,source="$(pwd)"/certs,target=/root/certs gnarkd:latest

FROM golang:latest AS builder 

RUN mkdir -p /go/src/github.com/consensys/gnark
COPY . /go/src/github.com/consensys/gnark/
WORKDIR "/go/src/github.com/consensys/gnark/gnarkd"
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo .
RUN mv /go/src/github.com/consensys/gnark/gnarkd/gnarkd /root/

FROM alpine:latest  
# RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /root/gnarkd .
CMD ["./gnarkd"]  